### ISSUE TITLE
Requisitos

### ISSUE THREAD

**Issue by renatoassis01** [igordcsouza/terraform-na-pratica#1]
Vou incluir um tópico curso e um link para criar uma conta no digital ocean ganhando 50 dolares de crédito

**Comment by renatoassis01** [comment]
acabei de ver que o item 3 do TNP 1.1 - Apresentacao do Modulo! contempla isso

**Comment by igordcsouza** [comment]
Eu ainda não gravei esse vídeo. Se quiser colocar o link lá fica a vontade. Se não eu coloco quando for gravar. ")
